### ISSUE TITLE
Add Documentation

### ISSUE THREAD

**Issue by chikeichan** [chikeichan/Trio#20]
DoD:
 - Document Trio using Github wiki

**Comment by DTsui** [comment]
Sorry but can you remove me from your email list? I don't know how you got
this email but I don't remember being part of your dev team.

Regardless, best of luck to your team.

-Damien

**Comment by chikeichan** [comment]
@DTsui Sorry about that. One of my collaborators has a very similar github handle to yours. I have fixed it now. Please let me know if you are still receiving notifications.

Thanks!

**Comment by chikeichan** [comment]
https://github.com/chikeichan/Trio/wiki
